

const DeleteAccountSteps = () =>
{
  return (
    <div className="delete-account-steps-section">
        <h2>How to Delete your Data</h2>
        <p className="delete-account-top-level">To delete your data you can request an account deletion in our app! This will delete all information immediately linked to you, your name, email, password, our generated ID linked to you, and all other information linked to that. However, anonymous info generated by your interaction with the app will not be deleted. </p>

        <h4>Instructions:</h4>
        <p className="delete-account-step-1">Firstly, navigate into your profile by clicking top right</p>

        <img className="delete-account-step" src="" />

        <p className="delete-account-step-2">Secondly, you should click the delete account button available to you in your account page</p>

        <img className="delete-account-step" src="" />

        <p className="delete-account-congrats">Congrats, you have successfully deleted your account!</p>
    </div>
  )
}
export default DeleteAccountSteps;
